// React imports
import React from 'react';
import { Text, ScrollView, StyleSheet, View } from 'react-native';


// Internal imports
import { scaledWidth, scaledHeight, normaliseFont } from 'src/util/dimensions';


/* Notes:

https://www.solidi.co/terms

*/




let horizontalRule = () => {
  return (
    <View
      style={{
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        marginHorizontal: scaledWidth(100),
      }}
    />
  )
}


let TermsAndConditions = () => {

let textGeneralTermsAndConditions = `
0.  The Important Bits
  This section contains the parts of the terms and conditions which result in the greatest misunderstandings. You must read the whole terms and conditions but we would like to draw your attention to the following points.
  1. You must supply your real name. Accounts created using fake names etc will be closed without warning. (Terms 6.2)
  2. You must be over 18 to use Solidi. (Terms 6.4)
  3. You must make payments from an account in your name. (Terms 6.5.3)
  4. You must not create more than ONE account without seeking prior permission from Solidi Support. (Terms 6.3)
  5. You must trade only with your own money. (Terms 6.6 and Terms 6.7)
  6. You understand that CryptoAssets are highly risky investments and are not subject to protection under the Financial Services Compensation Scheme or within scope of the Financial Ombudsman Service (Trading 9.2).
  Violation of the above terms will result in your account being suspended pending satisfactory ID verification and AML/KYC checks. In some cases accounts will be closed and details passed to the relevant authorities under the UK MLR2019 (si2019-1511) regulations.

  1.  About these Terms & Conditions
    1.  Solidi (the “website”) is an online service/platform owned and operated by Solidi Ltd.
    2.  The Platform enables Users to buy and sell Bitcoins and other crypto currencies.
    3.  These terms apply to use of any part for the Solidi Platform.
    4.  These terms should be read in conjunction with the following additional Terms / Policies as both will apply.
      1.  Privacy Policy
      2.  Trading Terms and Conditions
      3.  AML Policy
    5.  By using the Platform you are confirming that you are:
      1.  able to understand these terms and conditions.
      2.  accept these terms and conditions.
      3.  agree to abide by these terms and conditions.
      4.  are over the age of 18 (or older depending on the Age of Majority in your country)
    6.  We may make alterations to these term and conditions from time to time. We may notify you of key changes to these terms and conditions.

  2.  Definitions
    1.  In these Terms and Conditions the following Definitions are taken as:
      “account” - means an account of a User which is created when the user registers with the platform.
      “asset” means any item traded on the website. This would normally be a crypto currency, but is not limited to this.
      “AML” means Anti Money Laundering. It is the process of detecting assets (including money) generated from the proceeds of criminal activity.
      “Counterparty” means the User who take the opposite side to You in an executed Trade.
      “Customer”, “your”, “you” means a User of the Platform (either registered or unregistered)
      “Crypto Currency”,  “Digital Currency” means units of monetary value which are unique and unforgeable including (but not limited to) currencies such Bitcoin, Litecoin, Dogecoin.
      “off-exchange”, means that a currency is not held on Solidi systems. If any one currency of a currency pair is 'off-exchange' then generally settlement will be delayed until the currency has been paid to the seller.
      “on-exchange”, means that a currency is held on Solidi systems. If both currencies of a currency pair are 'on-exchange' then generally settlement will be instant and automatic.
      “Order” means an electronic order made by a User who wishes to trade an asset.
      “Platform”, “Online Service” means the website (“solidi.co” and all subdomains), API, trading platform, mobile applications owned and operated by Solidi Ltd.
      “settlement” means the exchange of an asset or money between two users to settle a debt resulting from a trade.
      “Solidi”, “Solidi FX”, “we”, “us”, “our” are references to the trading name “Solidi” of Solidi Ltd a limited company incorporated in England & Wales (reg no 09411526) with registered address at 27 Old Gloucester Street, London, WC1N 3AX.
      “trade” means an agreement between two users to exchange a quantity of an asset at a fixed price.
      “user” means an individual or corporate entity who uses the platform and is bound by these Terms and Conditions.
      “user content” means content generated by users of the Platform including (but not limited to) orders, prices, comments, settlements and any other information generated by a User or their interaction with the site.

3.  About “Solidi Ltd”
  1.  Solidi is the trading name of Solidi Ltd a limited company incorporated in England & Wales (reg no 09411526) with registered address at 27 Old Gloucester Street, London, WC1N 3AX
  2.  Solidi Ltd is registered with the Information Commisioners Office with registration number ZA142009.
  3.  Solidi Ltd is registered under the Money Laundering, Terrorist Financing and Transfer of Funds (Information on the Payer) Regulations 2017 as a cryptoasset business, registration number 928852. Our full registration details can be found at https://register.fca.org.uk/s/firm?id=0014G00002WMo9MQAT.
  3.  Solidi Ltd operate the Platform which matches Users buy and sell Orders, generating Trades and Settlements.

4.  Rights of Use
  1.  You have the right to use the Platform solely for the purpose of trading Crypto Currencies in accordance with our Trading Terms.

5.  Intellectual Property
  1.  Unless otherwise stated, all copyright, design rights, trademarks, patent rights, database schema, database content, source code, compiled code and any other intellectual property belong to and vest in us or are licensed to us.
  2.  All third party trade names, trade marks, design rights are the property of their respective owners and no warranty or representation is made or implied in relation to them.

6.  Restrictions and Obligations
  1.  You will not:
    1.  hack, crack, copy, modify, reverse engineer or create derivative works of this Platform or any part of it;
    2.  gain unauthorised access to any part of this Platform;
    3.  disclose your login credentials to any third party;
    4.  use identical login credentials as used on other platforms;
    5.  remove copyright, trademark or any other notices from this Platform;
    6.  create software which replicates the data or functionality in this Platform;
    7.  make any part of this website available to a third party;
    8.  use the Platform for any illegal or immoral purpose;
    9.  use the Platform in such a way as to adversely affect the Platform or the users of the platform including, but not limited to, spamming, marketing, excessive use and denial of service attacks.
    10.  attempt to do any of the above
  2. You agree to supply your REAL NAME. You are not permitted to use aliases, fake names, aka's etc.
  3. You agree to maintain only ONE account on Solidi unless otherwise agreed with Solidi Support in writing.
  4. You are the older of:
    1. 18 years of age or
    2. Age of Majority your country of residence.
  5. You will make payments in line with the following:
    1. You will use the UK Faster Payments System.
    2. You will use a UK bank account.
    3. You will use a bank account in your name.
    4. You will only use a single account to make payment unless you contact support with the details of any additional accounts.
  6. You will not make payments on behalf of anyone else.
  7. You will only trade with your own money. You agree there is no beneficial owner.

7.  Liability and Disclaimer
  1.  We provide and maintain the Platform on an "as is" and "as available" basis without any warranty or condition, whether express, implied or statutory.
  2.  We assume no liability or responsibility for any errors or omissions, delays, or failures in the Platform.
  3.  We do not verify or review any third party content (“User Content”) made available through the Platform.
  4.  Views expressed in User Content are those of the user and not those of Solidi Ltd.

8.  Termination
  1.  Without limiting any other rights we  may have, we may immediately cancel or suspend access to the Platform at any time without prior notice.
  2.  We may cancel or suspend your access to the Platform should we in our opinions believe you have breached any of these terms and conditions.
  3.  We will endeavour to cancel all outstanding orders promptly, but we will hold no liability whatsoever for the final position.
  4.  Upon account termination we will transfer all held funds to a single address / account (per currency) of your choosing except where clause 5 applies.
  5.  Where account closure is due to transaction/payment/identification issues or suspected fraud issues we may:
    1.  Restrict the return of funds to a single funding account and currency used previously to fund the Solidi account.
    2.  Liquidate positions in other currencies for return to the nominated funding account.
    3.  Where a funding account is no longer available (e.g. closed) then there will be a £15 charge to verify a new account.
  6.  Where subclause 5 applies we may, at our discretion, agree with you to a 2 hour time window to perform the liquidation and return the funds to enable you to re-purchase the funds with another party and minise price slippage.
  7.  Where subclause 5 or 6 is applied we will not be responsible for fees and/or price slippage incurred. In general we would aim, wherever possible, to avoid exercising subclause 5 but in certain situations due to legal, regulatory or customer protection issues, this will not be possible.

9. Complaints
  1. If you feel we have not met your expectations in any way, please let us know so that we can tackle the problem as quickly as possible. We have a three-step procedure to resolve your concerns.
    1. Tell us about your complaint and how you feel it should be resolved by contacting us using any of the methods on the Contact Us page (http://www.solidi.co/contactus). We will endevour to resolve your complaint by the end of the third working day after you contact us. If we cannot do this then we will write or email you within five working days to tell you what we have done to resolve the problem or to acknowledge your complaint and let you know when to expect our full response.
    2. Follow up with us and if needs be ask for the matter to be referred to a senior member of staff.
    3. If you disagree with the decision we make then you may be able to refer your complaint to the Financial Ombudsman Service free of charge.

10.  Governing Law and Dispute Resolution
  1.  These Terms & Conditions and the Solidi Platform are governed by the laws of England and Wales. All parties irrevocably agree that any dispute shall be settled under the exclusive jurisdiction of the English Courts and submitted to an English Court in Cambridge.
  2.  If any court or competent authority decides that any term of these Terms and Conditions is held to be invalid, unlawful or unenforceable to any extent, such term shall, to that extent only, be removed from the remaining terms, which shall continue to be valid to the fullest extent permitted by law.
  3.  Failure to enforce any part of these Terms and Conditions share not constitute a waiver of that or any other condition which may be enforce at any future juncture to it’s fullest extent.

v1.11  01 Jul 2021
`;

let textPrivacyPolicy = `
1.  Introduction
  1.  “Solidi” is the trading name of the crypto currency buying and selling service, provided at www.solidi.co and subdomains (hereafter referred to as the “Platform”) provided by Solidi Ltd (referred to as “we”, “us”).
  2.  We are committed to protecting your privacy when you use our Platform or communicate with us. This document describes how and when we collect, use and disclose your information.
  3.  This document should be read in conjunction with our Terms of Service. Definitions in the Terms of Service apply equally to this document. They are separated to create clarity.
  4.  For the purposes of the Data Protection Act 1998 (the Act), the Data Controller is Solidi Ltd of 27 Old Gloucester Street, London, WC1N 3AX. Our registration number is ZA142009

2.  Personal information collected about Users
  1.  Basic Information: When registering as a User we will collect some of the following information: name, email, address, postcode, phone number, bank account details, crypto currency wallet details.
  2.  AML Information: Depending on your usage level and patterns we may also request you provide information so that we can meet our AML / KYC obligations. These details may include (but are not limited to) a proof of address and a proof of identity such as your passport and a utility bill.
  3.  Trading Information: When you create an Order, execute a Trade or perform a Settlement we will store appropriate details to perform this function including but not limited to date, time, IP address, quantity, price, counterparty, order type, execution type.
  4.  Security Information: For your protection, the security of the Platform and to improve the Platform we may collect IP addresses, information about your browser and host device through which you access the Platform, browsing habits, click locations.
  5.  Optional / Research Information: We may from time to time ask for your opinion via methods including but not limited to surveys, feedback forms.

3.  Use of personal information
  1.  We use personal information for the following purposes:
    1.  to operate the Platform and grant You access to the Platform
    2.  to verify your Identity as required by AML legislation
    3.  to detect fraud and other malicious activity
    4.  to test the platform based on the same or  similar setup and usage habits of our Users.
    5.  to send out Newsletters, Surveys and other relevant targeted promotional material.
    6.  to publish anonymised trade information about the Platform including Trade flow.
    7.  to provide prices of the most recently executed trades.
  2. Our Lawful Processing Condition(s) under General Data Protection Regulations (Article 6, Section 1) are:
    1. Consent - the data subject has given consent to the processing of his or her personal data for one or more specific purposes
    2. Performance of Contract - processing is necessary for the performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract
    3. Compliance with Legal Obligation - processing is necessary for compliance with a legal obligation to which the data controller is subject

4.  When might we disclose personal information?
  Except when required by any applicable law or governmental, judicial or regulatory body we will not disclose your personal information to any third party, with the following exceptions:
  1.  To enable a Counterparty to Settle a Trade we will disclose Your payment information. You expressly allow this disclosure as part of the Privacy Policy and our Trade Terms and Conditions
  2.  To enable Solidi Ltd to instruct an appropriate third party to perform AML / KYC checks, including Identity Checks, we may disclose your Basic and AML Information.
  3.  To enable the prevention of fraud. In cases where fraud is suspected (such as when an account is in violation of our General Terms and Conditions and/or Trading Terms and Conditions) we may exchange information with third parties.
  4.  To enable sending of email / bulk information we may disclose your details to a third party.
  5.  To enable the operation of our helpdesk and ticketing system we may disclose your information to a third party.

5.  Service Announcements, Newsletters and other communications
  1.  From time to time we may send out service announcements, newsletters and other communications.
  2.  It is a condition of using the platform that you receive and read Service Announcements.
  3.  Newsletters and Other Communications are optional, opt-in and can be unsubscribed from at any time.

6.  Cookies
  1.  To operate the Platform we use Cookies for authenticating users, session tracking and maintaining information about the use of the platform.
  2.  The Platform is designed to work with Cookies enabled and may not work correctly with Cookies disabled.

7.  Storage of Personal Information
  1.  All data is stored securely on our servers and encrypted before transmission.
  2.  Where appropriate, data is securely encrypted online and only decrypted offline e.g. AML Information
  3.  We only store data on servers which we require to make the platform function. e.g. AML Documentation is not stored online.
  4.  We may from time to time need to move your data onto systems outwith the EEA. When we do so, we will anonymise your data where appropriate.

8.  Retention
  1. We will only store your data as long as it is needed to perform our duties under the folowing legislation:
     - UK Money Laundering, Terrorist Financing and Transfer of Funds Regulations 2017:
         - http://www.legislation.gov.uk/uksi/2017/692/pdfs/uksi_20170692_en.pdf
     - Money Laundering Regulations 2007 (SI 2007 No. 2157)
         - http://www.legislation.gov.uk/uksi/2007/2157/pdfs/uksi_20072157_en.pdf
  2. Specifically we are required to store your information for five years beginning from:
     - the date a business relationship ends
     - the date a transaction is completed

9.  Your rights & Access to your Information
  1.  Your personal data is protected in the UK by the Data Protection Act 1998.  This provides amongst other things that the data we hold about you should be processed lawfully and fairly.  It should be accurate, relevant and not excessive.  The information should, where necessary, be kept up to date and not retained for longer than is necessary.  It should be kept securely to prevent unauthorised access by other people.  You have the right to see what is held about you and correct any inaccuracies.
  2.  The Data Protection Act 1998 gives you the right to access information held about you. In accordance with the Act you may request access to your data at any time. An initial access request will be processed with no charge. Repeated or regular requests may be subject to a reasonable administration fee. Please email contact@solidi.co where we will be pleased to send you a Crypto Currency wallet address or Bank Details to make payment.

10.  Changes to our Privacy Policy
  1.  From time to time we may make updates to this Privacy Policy. When this happens we will update this page and email your about the update.

11.  Contact
  1.  If you have any questions, please do not hesitate to contact us at contact@solidi.co

v1.06  01 June 2021
`;

  let textTradingTermsAndConditions = `
1.  Introduction
  1.  “Solidi” is the trading name of a crypto currency trade matching service, provided at https://www.solidi.co and subdomains (hereafter referred to as the “Platform”) provided by Solidi Ltd (referred to as “we”, “us”).
  2.  We are committed to providing the best Crypto Currency Trading Platform. This document describes how our Trading Platform works, how we handle payments and the rules which apply to using the Trading Platform.
  3.  This document should be read in conjunction with our Terms of Service. Definitions in the Terms of Service apply equally to this document. They are separated to create clarity.

2.  High Level Overview
  1.  “Solidi” is a Crypto Currency trading platform. It matches Orders made by Users of the Platform who wish to either Buy(Bid) or Sell(Ask) a Crypto Currency pair or other Asset.
  2.  “Solidi” provides a number of methods to send/receive payment for the Orders made on the platform as described in the 'Settlements' section
  3.  For payment methods other than "Balance", it is the responsibility of the users arrange for Settlement (payment) of the trade to take place in a mutually agreed manner (usually FPS or Credit Card).
  4.  “Solidi Ltd” is the counterparty in all trades.

3. Escrow
  1. Escow was a service provided by Solidi for its Broker based platform where Solidi was not a counterparty. The Escrow ensured customer funds were safe should a payment dispute arise.
  2. Solidi withdrew broker support on 1st June 2021. As Solidi now holds funds for both side of trades, the Escrow service has also been withdrawn.
  3. All customer funds are held in our secure wallet system.

4.  Orders
  1.  Orders are
    1.  a User's intention to buy or sell a specific quantity of Crypto Currency.
    2.  legally binding once received by the Platform.
    3.  remain live on the Platform until filled or cancelled.
    4.  executed in real-time.
  2.  Order Payment Methods are the methods by which a customer settles a financial obligation arising from an order. The following methods are available depending on the customer account (ID verified, Address verified etc.):
    1. "Solidi"      - The customer is buying from Solidi. The customer sends payment to Solidi's bank account.
    2. "Credit Card" - The customer is buying from Solidi. The customer makes payment via their credit or debit card.
    3. "Balance"     - The customer is buying from Solidi. The payment is completed by a balance the customer holds with Solidi.
    4. "Broker"      - Historic payment method, closed in 1st June 2021.
  2.  Orders are submitted to the Platform where they will be matched with opposing Orders of the same price.
  3.  Orders remain on the Orderbook until they are matched against an opposing Order or until their User cancels them.
  4.  A User can cancel an Order, but they are still legally liable for any Trades created from that order until they receive a cancelled confirmation.
  5.  Users acknowledge that as a real-time platform, the status of a live Order displayed to the User is it’s status at the time the Platform generated the response (e.g. webpage) and may not be its current status (e.g. when attempting to cancel).
  6.  Users acknowledge that even if an Order appears to be unmatched / unfilled when they cancel it, in the time (typically milliseconds) it takes a cancel instruction to reach the Platform the Order may have matched / filed against an opposing Order, resulting in Trade Executions for which they will be legally liable.

5.  Trades
  1.  Trades:
    1.  Are generated as a result of two opposing Orders matching. They deplete the remaining quantity on their respective parent orders.
    2.  Are not necessarily of the same quantity as the orders but will be for the same unit price / rate.
    3.  Are a legally binding contract between two Users to exchange a specific quantity of Crypto or Fiat Currency for a specific quantity of Crypto or Fiat Currency.
    4.  Cannot be cancelled.
    5.  Must be Settled (paid for) promptly, usually automatically (via balance) or generally within 2 hours (via FPS, credit card etc).
  2.  Users may get multiple trades per order although the platform is designed in such a way that only Advanced Traders and Market Makers should have to deal with this.

6.  Settlements
  1.  Settlements are:
    1.  The process of indicating & tracking that a User has an obligation to make a payment towards a trade or group of trades.
    2.  Created for each trade or group of trades to show the current status of the payment for the trade(s).
    3.  Initially in an UNPAID state and will progress SENT, RECEIVED, COMPLETE.
    4.  Processed automatically by Solidi where possible (e.g. when a currency is on-exchange)
  2. Settlement Methods are:
    1.  Financial instruments external to Solidi used to pay/receive payment for orders and deposit / withdraw funds from Solidi. The specific Settlement Method used is selected by the Customer/User when creating an order.
    2.  Settlement Methods can include:
      1. UK Faster Payments
      2. Credit/Debit Card
      3. Crypto currency
  3.  When a User sends a Payment for an Order/Trade/Settlement they mark it as Paid. This updates the Settlements status to SENT.
  4.  When a Counterparty User (or Solidi) receives a Payment for an Order/Trade/Settlement they mark it as Received. This updates the Settlements status to RECEIVED.
  5.  Any Escrowed Payments are settled last, automatically, by the Solidi Platform when all non-escrowed payments have been marked as Received.
  6.  Users must adhere to the time constraints imposed during settlement to ensure the smooth and efficient operation of the platform.

7.  Incoming Payments
  0.  An incoming payment is a payment sent from a customer to Solidi.
  1.  A payment is defined as 'on time' when it arrives in the correct bank account / processed by the credit card processor within 2 hours from the point the customer clicks on 'I have Paid' or 2.5 hours from the initial order being made (whichever is shorter). For a payment to be considered 'on time' it must arrive for the correct amount, with the correct reference and the correct sender name so that it will be recognised automatically by Solidi and processed 'on time'.
  2.  A payment which is not 'on time' is considered as 'late'.
  3.  Late payments can be cause by, but not limited to:
    1. Incorrect Reference
    2. Incorrect Amount
    3. Incorrect Sender Name
    4. Sent as multiple payments
    5. Arrived out with the max 2h / 2.5h payment window
  4. Late payments are considered a breach of contract and may not be accepted at the agreed rate by the counterparty.
  5. In cases where the counterparty will not accept the late payment the customer will be offered the option of:
    1. Credited currency at the counterparty's current rate (if they have sufficient funds).
    2. Refunded within 24 hours (Mon-Fri) in line with Faster Payments terms and conditions.
  6. Multiple late payments may result in a standard fee (see FEES .6) being charged or the account being temporarily suspended or closed.
  7. Refunded payments will be charge the bank charges applicable to the counterparty (not exceeding FEES .6) if they can be sent by Faster Payments. Any other method will may incur a standard fee (see FEES .6) plus the cost of sending the payment - e.g. if the payment is from an international bank account then the charge would be the Standard Fee plus the cost of the International Payment.

8. Outgoing Payments
  0.  An outgoing payment is a payment sent from Solidi to a customer.
  1.  Customers can choose whether to have the payment sent instantly or within 8 hours. This is the time period for the payment to be sent and does not guarantee the time within which a payment will be received although normally this will be instantly.
  2.  Solidi agrees to send payments on a 'best endeavour' basis and will not be in breach of contract should they exceed the stated time period.
  3.  For the avoidance of doubt, with outgoing payments (tied to a trade) the fluctuation of the price of the underlying asset has no bearing on the sell contract regardless of the period between trade execution and settlement sending or receipt.
  4.  Late Payment rules do not apply to Outgoing Payments as Solidi always complete outgoing payments.
  5.  Customers must ensure their payment details are correct - the sending party is not liable for mistakes made with payment details supplied by the customer.
  6.  Confirmation of Payee is not required to be used by Solidi.
  7.  Where Confirmation of Payee is available, Solidi will still send a payment, even with a negative result via Confirmation of Payee. It is entirely the responsibility of the customer to make sure their payment details are correct.

9.  Pre-Purchase Funds
  0.  Tier 2 verified accounts are able to send Fiat funds to Solidi for the pre-purchase of Crypto.
  1.  Funds sent to Solidi can only be used to purchase currency from Solidi.
  2.  Funds sent to Solidi are held with either:
      1. Enumis Limited (reg 7441513), an Electronic Money Institution, regulated by the Financial Conduct Authority (FRN 900028).
      2. SettleGo Solutions Limited (reg 09570221), trading as OpenPayd, an Electronic Money Institution, regulated by the Financial Conduct Authority (FRN 900483).
  3.  Customers acknowledge that these funds are not eMoney as defined by the Electronic Money Regulations 2011 and are not subject to the protection of the Financial Services Compensation Scheme (FSCS) or within scope of the jurisdiction of the Financial Ombudsman Service.
  4.  All funds held with OpenPayd/Enumis are held in segregated accounts that are available only for the purposes of holding Solidi's funds.  This should ensure that if OpenPayd/Enumis ever become insolvent, Solidi's funds, including your GBP prepayment balance should be returned to us, on your behalf, in full (less any administrative costs applied by the insolvency practitioner), but it may take longer than funds covered under the FSCS.
  5.  Customer prepayment funds held with OpenPayd/Enumis are held in a segregated account (separate from Solidi funds) that is available only for the purposes of holding customer prepayments. This should ensure that if Solidi ever become insolvent your GBP prepayment balance should be returned to you in full (less any administrative costs applied by the insolvency practitioner), but it may take longer than funds covered under the FSCS.
  6.  All prepurchase funds must come from a bank account in your name.
  7.  Funds from bank accounts not in your name will be returned to the sender and a standard fee (see FEES .6) may be applied to your account.
  8.  Pre-Purchase funds with Solidi earn no interest.
  9.  Withdrawals must be to a bank account in your name.
     1.  We will generally only send funds to an account you have sent from.
     2.  To send funds to a new account (which you have not previously sent from) we will require to verify the account owner. We will attempt to do this via Confirmation of Payee if available.
     3.  In the absence of a successful Confirmation of Payee verification, we will request to see proof of account ownership usually via one of the following:
        1.  Send funds from the account.
        2.  Photograph of the bank card (including name, sortcode and account number)
        3.  Photograph of the full bank statement (including name, sortcode and account number) dated in the last 3 months.
  10.  Solidi may charge fees for deposits and withdrawals. Any fees charged will be clearly displayed at the point of depositing / withdrawing.
  11.  Frequent Deposits / Withdrawals
     1. Frequent deposits are defined as deposits which are being made frequently and possibly also in conjunction with withdrawals with little / no 'buying' or 'selling' activity, possibly in the absence of Solidi charging for Deposit/Withdrawals.
     2. If in our opinion your deposits / withdrawals are of a level which we find unsustainable we may start applying a charge equivalent to our banking fees & administrative time to your account to cover the costs of the deposits / withdrawals.
  12.  Spam Deposits / Withdrawals
     1. Spam deposits / withdrawals are defined as deposits which in the opinion of Solidi have no useful purpose and were only conducted to increase the costs of Solidi.
     2. Examples of spam deposits / withdrawals include but are in no way limited to:
        1. Multiple small deposits made in a short period.
        2. Deposits made from multiple accounts not in your name / missing a reference.
     3. When Solidi detect spam deposits we may at our sole discretion raise a complaint with the sending bank.
        1. In such circumstances the full cost of the banking fees associated with the deposits would be charged to the customer.
        2. If the cost of the banking charges exceeds the customers balance then we will issue an invoice for the shortfall.
        3. In all instances a charge set out in the FEES section will be levied to the account.

10.  Crypto Deposits & Cold Storage
  1.  Deposits are amounts of crypto currency held by Solidi on behalf of its users.
  2.  All deposits are converted to a balance on receipt and held in our database as liability on Solidi Ltd for the same amount of deposited currency.
  3.  Deposits are held in cold storage for customer's security.
  4.  Solidi will process most withdrawals from the company owned hot wallet without requiring a specific withdrawal from cold storage.
  5.  Frequent Deposits
     1. Frequent deposits are defined as deposits which are being made frequently and possibly also in conjunction with withdrawals with no 'buying' or 'selling' activity.
     2. Deposits in Crypto Currency come with a cost which is normally covered by Solidi, but if in our opinion your deposits are of a level which we find unsustainable we may start applying a charge equivalent to the network fee to your account to cover the costs of the deposits.
  6.  Spam Deposits
     1. Spam deposits are defined as deposits which in the opinion of Solidi have no useful purpose and were only conducted to increase the costs of Solidi.
     2. Examples of spam deposits include but are in no way limited to:
        1. Multiple small deposits made in a short period.
        2. Transactions where multiple outputs are used to create multiple deposits to Solidi for no apparent reason.
     3. When Solidi detect spam deposits we may at our sole discretion sweep the multiple small deposits into a single output using a standard priority transaction.
        1. In such circumstances the cost of the transaction would be charged to the customer.
        2. If the cost of such a transaction exceeds the deposited funds then the deposited funds would be forfeited.
        3. In all instances a charge set out in the FEES section will be levied to the account.

11. Crypto Withdrawals & Cold Storage
  1.  Withdrawals are amounts of crypto currency send by Solidi on the instruction of its customer.
  2.  Withdrawals are sent on a best endeavour basis in the time specified. This specified time is the time period for the withdrawal to be sent / broadcasted to the crypto network and does not guarantee the time within which the funds will be confirmed by the network or received by the recipient.
  3.  From time to time it may not be possible to send withdrawals within the timeframe specified. In such circumstances Solidi will hold no liability for any delay or loss incurred.
  4.  Examples of when withdrawals may be delayed includes, but are not limited to:
     1. Security checks.
     2. Hot wallet being restocked.
     3. Incorrect address being supplied.
  5.  Solidi will process most withdrawals from the company owned hot wallet without requiring a specific withdrawal from cold storage.
  6.  Occasionally Solidi may have to withdraw funds from cold storage to process a withdrawal. This is done on a 'best endeavours' basis and places no guarantee on the withdrawal period.
  7.  Specifically the customer agrees that if they partake in an ICO/STO/IEO or some other form of investment (time sensitive or otherwise), Solidi will hold no responsibility for the timely delivery of funds to the recipient and that should they require delivery in a specific timeframe they must withdraw to their own wallet first.
  8. Frequent Withdrawals
     1. Frequent Withdrawals are defined as withdrawals which are being made frequently and possibly also in conjunction with deposits with no 'buying' or 'selling' activity.
     2. Withdrawals in Crypto Currency come with a cost which can be covered by Solidi with our Free Withdrawal service, but if in our opinion your withdrawals are of a level which we find unsustainable we may start applying a charge equivalent to the network fee to your account to cover the costs of the withdrawals, even if you opt to use the Free Withdrawal service.
  9. Spam Withdrawals
     1. Spam Withdrawals are defined as withdrawals which in the opinions of Solidi have no useful purpose and were only conducted to increase the costs of Solidi.
     2. Examples of spam withdrawals include but are in no way limited to:
        1. Multiple small withdrawals made in a short period.
        2. Withdrawals made to your own Solidi address.
        3. Multiple withdrawals to the same address in a short period.
     3. When Solidi detect spam withdrawals we may at our sole discretion refuse to process the withdrawals.
        1. In such circumstances your account would be locked from withdrawal pending investigation.
        2. Following completion of the investigation we may do one of the below. This is not an ordered list and account closer may be the outcome of a first investigation and no prior warnings.
          - Nothing, simply re-enable the account.
          - Issue a polite reminder regarding these terms.
          - Issue a final warning.
          - Close the account in question.
        3. A charge set out in the FEES section may be levied to the account.

12.  Fees
  1.  Buying and Selling crypto currency has no additional fee over the base price quoted on the website and any relevant bank fees.
  2.  Depositing Crypto Currency to Solidi may require the payment of a fee broadly calculated equivalent to the network fees payable when sending the crypto currency that was deposited as the time of the deposit. This is usually the cost of spending the UTXO (in Bitcoin, other currencies vary) generated by the deposit.
  3.  Withdrawing Crypto Currency from Solidi may require the payment of a fee broadly equivalent to the cost of the destination address used in the transaction plus the cost of the change address split by the total number of destination addresses in the transaction (this varies for each crypto currency).
  4.  Solidi may calculate fees outlined in points .2 and .3 above based on the average of the previous day / weeks fees, rounded to an appropriate number of decimal places for presentation (e.g. 0.001 rather than 0.00112919) to enable fees to be displayed to the user before a deposit or withdrawal takes place.
  5.  Solidi may from time to time offer fee free periods. Doing so does not invalidate our fee structure which may be re-introduced without notice.
  6.  Solidi may at its discretion charge a fee for the involvement of our support team to correct problems with orders. Such a fee will be levied at £15 per incident and is intended to discourage careless mistakes in orders to enable our support team to concentrate their time on productive tasks and is not intended as a profit making endeavour.
  7.  For a complete breakdown of our fees, please see https://www.solidi.co/fees

13.  Blockchain Forks
  The purpose of this section is to protect Solidi from the costs of supporting a blockchain fork.
  1.  All funds on Solidi are held as IOU's on the specific blockchain of deposited funds. An IOU for 1 BTC will result in the payment of 1 BTC at a future point.
  2.  Solidi has no obligation to support any currency resulting from a blockchain fork. Solidi's default position is that we will not support a currency resulting from a blockchain fork.
  3.  Solidi will endeavour, but is not obliged, to warn users of future blockchain forks including our position on such forks to give customers sufficient time to withdraw their funds.
  4.  Before, during and following a blockchain fork, Solidi may at its discretion, turn off withdrawals and deposits from some or all currencies. We will endeavour to provide warning of such events.
  5.  In the event Solidi decides to implement support there is no guarantee of the timeframe to implement such support.
  6.  Solidi may pass the costs of supporting a new blockchain onto the holders of funds on the new blockchain at the point of the fork. Fees will be applied at an exchange rate determined at the point the support is activated. In this event the costs shall not exceed 25% of the funds stored on the new blockchain or £20,000 (whichever is lower).

14.  Disputes
  1.  Our dispute resolution process was part of our broker service. It was user to resolve dispute arising between Brokers and Customers.
  2.  Solidi withdrew broker support on 1st June 2021 and along with this we withdrew our Dispute resolution process for Brokers and Customers.
  3.  Customers who have a complaint or dispute with Solidi should follow our complaints procedure (see our standard terms and conditions).

15.  Chargebacks (UK FPS & Credit Card)
  Chargebacks are a process where a User attempts to reverse a payment made to Solidi. Sometimes this is due to a dispute regarding a transaction usually this is just fraud. Chargebacks are expensive to deal with in terms of time and money. Solidi has a complaints process to deal with all disagreements which MUST be used prior to raising a chargeback. We are proud that our complaints process has resolved all complaints fairly and thus ensured no customer have ever raised a chargeback.
  1.  Users agree not to use chargebacks without having completed Solidi's complaints process. The complaints process exists to resolve all disagreements fairly and impartially.
  2.  Users agree that should a chargeback be received by Solidi, without the complaints process being completed, that the User will pay all costs associated with the chargeback, including:
      1. Bank Fees
      2. Legal Fees
      3. Staff Costs
      4. Conseqential Losses
  3.  Chargebacks received without the dispute resolution process being completed will result in Solidi account closure and the users details being shared with third party fraud prevention services.

v1.13  01 Jan 2022
`;

  let textOverTheCounterTermsAndConditions = `
1.  Introduction
  1.  “Solidi OTC” is the trading name of a crypto currency Over-The-Counter service, provided by telephone and at https://www.solidi.co and sub-domains (hereafter referred to as the “Platform”) provided by Solidi Ltd (referred to as “we”, “us”).
  2.  We are committed to providing the best OTC Crypto Currency trading service. This document describes how our OTC service works, how we handle payments and the rules which apply to using the service.
  3.  This document should be read in conjunction with our General Terms and Conditions of Service and our Trading Terms and Conditions. Definitions in the Terms of Service and Trading Terms and Conditions will apply equally to this document. They are separated to create clarity.
  4.  To the extent that there is an inconsistency between these OTC Terms and Conditions and either the General Terms and Conditions or the Trading Terms and Conditions, the terms of these OTC Terms and Conditions will govern and control. Any capitalized term not defined herein shall have the meaning set forth in the General Terms and Conditions.

2.  High Level Overview
  1.  “Solidi” is a Crypto Currency trading platform. It matches Orders made by Users of the Platform who wish to either Buy(Bid) or Sell(Ask) a Crypto Currency pair or other Asset.
  2.  “Solidi OTC” is an Over-The-Counter Crypto Currency buying and selling service for high volume buying and selling in any crypto currency including crypto currencies which are not yet listed on Solidi.
  3.  “Solidi OTC” handles the end to end process of sourcing liquidity providers for large crypto currency transactions as well as liquidity in obscure assets.
  4.  All OTC trades are final and except where a delayed settlement has been afforded must be pre-funded by depositing sufficient crypto currency or fiat currency into the appropriate wallet on Solidi.
  5.  All OTC quotes are estimates and except where an execution price has been agreed in writing the customer accepts that final execution price / quantity may deviate from the quoted price due to market fluctuations, network fees, liquidity issues and intermediary exchange costs.
  6.  All counterparties to the OTC trade are anonymous with Solidi acting as the intermediary.

3.  Quotes
  1.  Upon request, Solidi OTC will provide a verbal or written quote for the purchase of crypto currency in the customers pre-determined quote asset (usually GBP).
  2.  Quotes are estimates and except where an execution price has been agreed (via additional fee) in writing the customer accepts that final execution price / quantity may deviate from the quoted price due to market fluctuations, network fees, liquidity issues and intermediary exchange costs.
  3.  Quotes are only converted to Orders when the customer confirms their acceptance in written email communication and has sufficiently pre-funded their account (or delayed settlement has been agreed).

4.  Orders & Execution
  1.  Orders are
    1.  a Customer's intention to buy or sell a specific quantity of Crypto Currency.
    2.  legally binding once received by the OTC Desk.
    3.  remain live until filled or advised in writing and agreed by all counterparties to be cancelled.
    4.  executed on a best endeavour basis (unless an execution price has been agreed).
  2.  Orders are normally executed and settled by close of business unless previously advised due to the order size / obscurity of the assets to be purchased.

5.  Storage, Deposit & Withdraw
  1.  All purchased currency is stored with Solidi without charge.
  2.  Deposits & Withdraws of currencies supported on the main Solidi website can be made in the usual way.
  3.  Deposits in currencies not supported on the main Solidi website:
      1.  Can be made by requesting a deposit address.
      2.  The OTC team will supply you with a deposit address and confirm safe receipt via secure communications.
      3.  You must not deposit until the OTC team have confirm the safe, unaltered address.
  4.  Withdraws in currencies not supported on the main Solidi website:
      1.  Can be made by supplying a deposit address and amount to Solidi.
      2.  The OTC team will confirm with you safe receipt via secure communications.
      3.  The OTC team will process the withdraw, usually within 2 business days.
  5.  Solidi accepts no responsibility for delays with withdraw or deposit.

6.  Pre-Funding
  1.  Except for orders where you are afforded delayed settlement (section 6) all orders must be paid for with cleared funds before the order is executed.
  2.  Cleared funds are defined as:
     1. GBP - Funds paid to Solidi's Customer Account from the clients normal funding account.
     2. Crypto - Funds cleared on the crypto network with Solidi's normal minimum number of confirmations.

7.  Delayed Settlement
  1. Solidi doesn't currently support delayed settlement. All Orders must be pre-funded.

8.  Fees
  1.  All OTC quotes include the following fees in the price:
    1.  Solidi commission
    2.  FX rates (where required)
    3.  Network fees to move the currency to Solidi
  2. OTC quotes specifically do not include the following (this is not an exhaustive list):
    1.  Network fees to transfer from Solidi
    2.  Network / deposit fees for depositing the settlement currency.
    3.  Cancellation fees (if the Order is cancelled during partial execution)

9.  Cancellation / Withdrawal
  1.  Requests to cancel an Order must be made in writing.
  2.  Upon receipt of a cancellation request, Solidi will provide a written update of Order's execution status including quantities executed and a cancellation fee quote.
  3.  Customers must provide written confirmation of their agreement to the cancellation quote to begin the cancellation process.
  4.  Cancellation requests will not halt the execution of an order until the the cancellation quote confirmation is received and forwarded to all counterparties.
  5.  Specially, customers acknowledge / agree that:
      1.  Cancellation is not always possible.
      2.  Cancellation incurs additional fees.
      3.  Cancellation quote confirmations may be received after the order has completed executing in which case they are null and void.

v1.01  08 Apr 2020
`;

  return (
    <View>

        <View style={styles.sectionHeading}>
          <Text style={styles.sectionHeadingText}>General Terms & Conditions</Text>
        </View>

        <Text>{textGeneralTermsAndConditions}</Text>

        {horizontalRule()}

        <View style={styles.sectionHeading}>
          <Text style={styles.sectionHeadingText}>Privacy Policy</Text>
        </View>

        <Text>{textPrivacyPolicy}</Text>

        {horizontalRule()}

        <View style={styles.sectionHeading}>
          <Text style={styles.sectionHeadingText}>Trading Terms & Conditions</Text>
        </View>

        <Text>{textTradingTermsAndConditions}</Text>

        {horizontalRule()}

        <View style={styles.sectionHeading}>
          <Text style={styles.sectionHeadingText}>Over-The-Counter (OTC) Terms & Conditions</Text>
        </View>

        <Text>{textOverTheCounterTermsAndConditions}</Text>


    </View>
  )

}


let styles = StyleSheet.create({
  sectionHeading: {
    marginTop: scaledHeight(20),
    marginBottom: scaledHeight(20),
  },
  sectionHeadingText: {
    fontSize: normaliseFont(16),
    fontWeight: 'bold',
  },
  bold: {
    fontWeight: 'bold',
  },
});


export default TermsAndConditions;
