
export const mainPanelStates = [
  'Buy',
  'Sell',
  'Assets',
  'History',
  'Send',
  'Receive',
  'Notifications',
  'Settings',
  'Test',
  'Login',
  'PIN',
  'ChooseHowToPay',
  'MakePayment',
  'WaitingForPayment',
  'PaymentNotMade',
  'PurchaseSuccessful',
  'InsufficientBalance',
  'ReadArticle',
  'ChooseHowToReceivePayment',
  'RequestTimeout',
  'SaleSuccessful',
  'PersonalDetails',
  'ContactUs',
  'BankAccounts',
  'Security',
  'RequestFailed',
  'Error',
  'SendSuccessful',
  'Authenticate',
  'Register',
  'SupportTools',
  'LimitsExceeded',
  'IdentityVerification',
  'ResetPassword',
  'MakePaymentOpenBanking',
  'SolidiAccount',
  'CloseSolidiAccount',
  'RegisterConfirm',
  'RegisterConfirm2',
  'AccountUpdate',
];

export default mainPanelStates;
